### ISSUE TITLE
HTTP Status Codes

### ISSUE THREAD

**Issue by bvdh** [cds-hooks/docs#83] opened 2017-09-08 16:34 UTC
Section "HTTP Status Codes" seems to suggest that only "200 OK" is allowed.
What to do in in an error situation?
I suggest to add/allow responses in the 400 and/or 500 range.

**Comment by brynrhodes** [comment] 2017-09-12 19:06
This seems to be a duplicate of #93?

**Comment by kpshek** [comment] 2017-09-13 03:44
I agree @brynrhodes. Closing this as a duplicate of #93.

**Closed by kpshek** 2017-09-13 03:44 UTC
Labels: duplicate
