### ISSUE TITLE
Use Parameters as the data type for the prefetch in a CDS Service request

### ISSUE THREAD

**Issue by euvitudo** [cds-hooks/docs#37] opened 2017-05-05 03:59 UTC
I would like to suggest that Prefetch (in CDS Request) be defined as a Parameters resource.  This way we can include any kind of resource, including OperationOutcomes, esp. for those pre-fetch requests that fail (to possibly address a comment by @jmandel in #5 ).  This would also increase the flexibility in specifying the type of parameter value (i.e., value[x], resource
or part), including not limiting the parameter value to a resource.

**Comment by jmandel** [comment] 2017-05-05 15:55
I'm not sure I follow. You're describing changes to the "request", but the desired behavior (like "including OperationOutcomes") is about the response. Could you show an example of what you mean @euvitudo? For example, could you translate the following?

``
{
  "id": "http://hooks.fhir.me:8082/cds-services/patient-hello-world",
  "url": "http://hooks.fhir.me:8082/cds-services/patient-hello-world",
  "enabled": true,
  "hook": "patient-view",
  "prefetch": {
    "patientToGreet": "Patient/{{Patient.id}}",
    "recentSBP": "Observation?patient={{Patient.id}}&code=8480-6&_sort:desc=date&_limit=1"
  }
}
```
In this example, it's perfectly possible for the server to respond with a Patient resource for the `patientToGreet` and an OperationOutcomes if the `recentSBP` fails (or a bundle, if things work; and the bundle can also include an OperationOutcome in Bundle.entry where mode=`outcome`, if the request worked but the server has some outcome notes to share).

**Comment by euvitudo** [comment] 2017-05-05 16:27
This is specifically with the request to the CDS Service.  In #5 you mention:

> CDS Services need a clear way to tell the difference between "this query wasn't run by the EHR as part of prefetch" vs. "the query was run and returned no results, or an error".

For example (not a very good example, but it conveys the intent of the suggestion), if you have an invalid patient id (the prefetch fails on this) you then submit the following to the CDS Service:

```
{
  "hookInstance": "d1577c69-dfbe-44ad-ba6d-3e05e953b2ea",
  "fhirServer": "http://hooks.smarthealthit.org:9080",
  "hook": "patient-view",
  "redirect": "http://hooks2.smarthealthit.org/service-done.html",
  "user": "Practitioner/example",
  "context": [

  ],
  "patient": "1288992",
  "prefetch": {
    "patientToGreet": {
      "response": {
        "status": "400 Not Found"
      },
      "resource": {
        "resourceType": "OperationOutcome",
        "id": "15060",
        "issue": [
          {
            "severity": "warning",
            "code": "informational",
            "details": {
              "text": "Resource request returns no results.",
              "coding": [
                {
                  "system": "urn:oid:1.2.3.4.5",
                  "code": "1234",
                  "display": "Resource request returns no results."
                }
              ]
            }
          }
        ]
      }
    }
  }
}
```

If, however, you're using a Parameters, this would look like:

```
{
  "hookInstance": "d1577c69-dfbe-44ad-ba6d-3e05e953b2ea",
  "fhirServer": "http://hooks.smarthealthit.org:9080",
  "hook": "patient-view",
  "redirect": "http://hooks2.smarthealthit.org/service-done.html",
  "user": "Practitioner/example",
  "context": [

  ],
  "patient": "1288992",
  "prefetch": {
    "resourceType": "Parameters",
    "parameter": [
      {
        "name": "patientToGreet",
        "resource": {
          "resourceType": "OperationOutcome",
          "id": "15060",
          "issue": [
            {
              "severity": "warning",
              "code": "informational",
              "details": {
                "text": "Resource request returns no results.",
                "coding": [
                  {
                    "system": "urn:oid:1.2.3.4.5",
                    "code": "1234",
                    "display": "Resource request returns no results."
                  }
                ]
              }
            }
          ]
        }
      }
    ]
  }
}
```
Using this, a CDS Service can use a well-known format for understanding the failed prefetch operation and take appropriate action.

As a further note, the Discovery might look like this:

```
{
  "services": [
    {
      "hook": "patient-view",
      "name": "Static CDS Service Example",
      "description": "An example of a CDS service that returns a static set of cards",
      "id": "static-patient-greeter",
      "prefetch": {
        "resourceType": "Parameters",
        "parameter": [
          {
            "name": "patientToGreet",
            "valueString": "Patient/{{Patient.id}}"
          },
          {
            "name": "medications",
            "valueString": "MedicationOrder?patient={{Patient.id}}"
          }
        ]
      }
    }
  ]
}
```

**Comment by jmandel** [comment] 2017-05-05 16:42
Thanks - I see what you're describing now! Could you help me understand what you see as the benefits of this approach?

**Comment by euvitudo** [comment] 2017-05-05 18:10
- Using Parameters is similar with the current prefetch definition (discovery and request) specified in the existing CDS Hooks API, and provides a richer set of semantics for reasoning about potential errors, empty responses, etc.
- The ability to explicitly convey a datatype, a Resource, or a multi-part parameter; explicit types are easier to reason about.
- It is more consistent with Clinical Reasoning, as they use Parameters to pass input.

**Comment by jmandel** [comment] 2017-05-05 18:41
OK. For history here: we used to use Parameters for _all CDS Hooks operations_, and after careful evaluation, we decided they were verbose and not providing a lot of value...

**Comment by kpshek** [comment] 2017-05-05 18:48
Thanks for the additional details @euvitudo.

@jmandel is correct that we haven't used the Parameters resource, having made this change a year ago.

Regarding Clinical Reasoning, @brynrhodes, @isaacvetter, and myself have been working together for the past several months to see how we can better align both projects. We'll be posting a write-up for our proposals to the two communities for feedback which aims to address your comment on the two projects.

As an aside, and I know you called this out as not a good example 😛, but we should never see a 404 on a patient prefetch for a patient-view hook. Since the EHR is in complete control in this use case, not finding the patient whose chart the clinician just opened would be a major issue.

**Comment by euvitudo** [comment] 2017-05-05 18:51
Thanks.  I look forward to the write-up.

**Comment by kpshek** [comment] 2017-05-05 18:52
For reference, here are a few Google Group posts on the design changes from last year:

- https://groups.google.com/d/msg/cds-hooks/frHmx2VCvIE/TEWxUXLzEwAJ
- https://groups.google.com/d/msg/cds-hooks/CpTDT35cVu0/OU_LnD_aBwAJ

**Comment by euvitudo** [comment] 2017-05-05 19:01
For clarification, I am in no way advocating the use of Parameters for the CDS Hooks data model--just the prefetch element.

**Comment by euvitudo** [comment] 2017-05-07 00:35
Below is a use case to consider in this context:

This gist ([fhir.cygni.cc.500.json](https://gist.github.com/euvitudo/8080a3965b1f4e8abaea7bfb49365f05)) is a call to the the service on fhir.cygni.cc that has been failing--returning a 500--to the caller.  It's caused by the resource turning out to be null (I believe we catch the HAPI-FHIR parse exception and this yields a null resource--arguably a bug in our code that may need to more properly addressed--or at minimum-level effort, an error indicating the issue instead of a sending back the raw 500).

However, if the calling code has created an OperationOutcome instead of putting the raw HTML into the `resource`, this could have been more easily handled.

**Comment by jmandel** [comment] 2017-05-07 08:42
Ah -- so obviously we want to be clear that "resource" is only for FHIR resources. We wouldn't expect to see an EHR populate a prefetch resource body with an HTML document showing an error page :-) `"resource": null` might be the right thing there.

**Comment by euvitudo** [comment] 2017-05-07 08:48
Interesting.  So instead of providing information as to why the response.status is 404 (as can be provided in an OperationOutcome) you'd rather have a null resource?  The CDS Service would then need to either re-request the data from the FHIR server (getting the OperationOutcome itself) or simply ignore the null and give an unexpected result (e.g., no result).

**Comment by kpshek** [comment] 2017-05-07 08:52
We certainly should document the expected behavior for this edge case identified in the [aforementioned gist](https://gist.github.com/euvitudo/8080a3965b1f4e8abaea7bfb49365f05)..

`"resource": null` is one way. Another would be for the EHR to not include that particular prefetch key/value at all. In the case of the gist, that means the prefetch object would not contain the `medicationOrders` and `patient` keys at all.

**Comment by kpshek** [comment] 2017-06-05 21:18
@euvitudo - This thread has moved towards clearing defining how we handle error scenarios with prefetched data. After discussion with @brynrhodes and @isaacvetter, we believe this will be addressed by #5. Provided you agree, do you mind if I close this?

**Comment by euvitudo** [comment] 2017-06-06 04:43
Is there a single location with all the decisions that are being documented?  The spaghetti created by these set of issues is less than tolerable.

**Closed** 2017-06-06 05:02 UTC
Labels: api-design

**Comment by kpshek** [comment] 2017-06-06 05:04
Thanks for agreeing to address this in #5, @euvitudo. I understand the challenges in keeping track of the discussion across these issues -- it's a challenge for me too! I expect our decisions to result in concrete pull requests and changes to our documentation.
