### ISSUE TITLE
Indicate the HL7 FHIR version for each CDS Service definition in the Discovery endpoint

### ISSUE THREAD

**Issue by tbatlarge** [cds-hooks/docs#11] opened 2016-09-17 15:55 UTC
Each hook is specific to a FHIR version. (The prefetch URLs are version-specific.) Therefore a property should be added to "#/definitions/CDS Service" that specifies the FHIR version for that hook.

**Comment by kpshek** [comment] 2016-09-17 16:05
👍

I was talking offline with @tbatlarge when he brought this up and it mirrors thoughts I had yesterday around this very need. CDS Services will undoubtably understand a particular version of FHIR. I told him to log this issue as I thought I had not logged an issue yet for this.

However, @tbatlarge just pointed out that indeed I did! Closing as a duplicate of #3.

Thanks @tbatlarge for logging this anyway though! At least we've confirmed someone else agrees with me 😜

**Closed by kpshek** 2016-09-17 16:05 UTC
